runtime: nodejs22
env: standard
instance_class: F1

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

inbound_services:
 - warmup
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 4
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 500ms
  max_pending_latency: automatic
  max_concurrent_requests: 20
