steps:
  # Install node packages
  - name: node:16.13.1
    entrypoint: npm
    args: ["install"]

  # Build
  # - name: node:16.13.1
  #   entrypoint: npm
  #   args: ["run", "build"]

  # Deploy to google cloud app engine
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--version=dev", "--no-promote"]

timeout: "1600s"